#!/bin/sh -e

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /bin/nc /bin
copy_exec /bin/tar /bin
copy_exec /bin/sync /bin
copy_exec /sbin/mkfs.ext4 /sbin
copy_exec /sbin/fdisk /sbin
copy_exec /sbin/kpartx /sbin
copy_exec /usr/bin/mkpasswd /sbin
# "config files" used to setup the img
copy_exec /etc/resolv.conf /sbin
copy_exec /etc/network/interfaces /sbin
copy_exec /etc/kernel-img.conf /sbin
