#!/bin/sh -e

PREREQ=""

prereqs()
{
        echo "$PREREQ"
}

case $1 in
# get pre-requisites
prereqs)
        prereqs
        exit 0
        ;;
esac

. /usr/share/initramfs-tools/hook-functions

copy_exec /sbin/resize2fs /sbin
copy_exec /sbin/e2fsck /sbin
copy_exec /sbin/tune2fs /sbin
copy_exec /sbin/sfdisk /sbin
copy_exec /sbin/fdisk /sbin
copy_exec /bin/sync /bin
copy_exec /usr/bin/bc /bin
